language: node_js
node_js:
  - "node"
script:
  - npm test
  - npm run site
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: docs
  